version: '3.8'
services:
    node:
        container_name: project-api-node
        # image: 'node:latest'
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /home/node/app
        user: 'node'
        command:
            - /bin/sh
            - '-c'
            - 'npm install --unsafe-perm && chown -R node:node /home/node/app/node_modules && npm start'
        ports:
            - '3000:3000'
        volumes:
            - './src:/home/node/app'
        links:
            - mongo
    mongo:
        container_name: project-api-db
        image: mongo
        ports:
            - "27017:27017"